export const targetList = {
    "1": "1 Cent,Australian dollar,australia",
    "2": "5 Centavos,Brazilian Real,brazil",
    "3": "5 Won,Korean Won,south_korea",
    "4": "10 Won,Korean Won,south_korea",
    "5": "50 Won,Korean Won,south_korea",
    "6": "100 Won,Korean Won,south_korea",
    "7": "500 Won,Korean Won,south_korea",
    "8": "1 Sen,Malaysian Ringgit,malaysia",
    "9": "5 Sen,Malaysian Ringgit,malaysia",
    "10": "10 Sen,Malaysian Ringgit,malaysia",
    "11": "20 Sen,Malaysian Ringgit,malaysia",
    "12": "50 Sen,Malaysian Ringgit,malaysia",
    "13": "10 Centavos,Brazilian Real,brazil",
    "14": "5 Centavos,Mexican peso,mexico",
    "15": "10 Centavos,Mexican peso,mexico",
    "16": "20 Centavos,Mexican peso,mexico",
    "17": "50 Centavos,Mexican peso,mexico",
    "18": "1 Peso,Mexican peso,mexico",
    "19": "2 Pesos,Mexican peso,mexico",
    "20": "5 Pesos,Mexican peso,mexico",
    "21": "10 Pesos,Mexican peso,mexico",
    "22": "5 Cents,New Zealand dollar,new_zealand",
    "23": "10 Cents,New Zealand dollar,new_zealand",
    "24": "25 Centavos,Brazilian Real,brazil",
    "25": "20 Cents,New Zealand dollar,new_zealand",
    "26": "50 Cents,New Zealand dollar,new_zealand",
    "27": "1 Dollar,New Zealand dollar,new_zealand",
    "28": "2 Dollars,New Zealand dollar,new_zealand",
    "29": "50 Ore,Norwegian Krone,norway",
    "30": "1 Krone,Norwegian Krone,norway",
    "31": "5 Kroner,Norwegian Krone,norway",
    "32": "10 Kroner,Norwegian Krone,norway",
    "33": "20 Kroner,Norwegian Krone,norway",
    "34": "1 Rupee,Pakistan Rupee,pakistan",
    "35": "1 Real,Brazilian Real,brazil",
    "36": "2 Rupees,Pakistan Rupee,pakistan",
    "37": "5 Rupees,Pakistan Rupee,pakistan",
    "38": "10 Rupees,Pakistan Rupee,pakistan",
    "39": "1 Sentimo,Philipine peso,philippines",
    "40": "5 Sentimos,Philipine peso,philippines",
    "41": "10 Sentimos,Philipine peso,philippines",
    "42": "25 Sentimos,Philipine peso,philippines",
    "43": "1 Piso,Philipine peso,philippines",
    "44": "5 Piso,Philipine peso,philippines",
    "45": "10 Piso,Philipine peso,philippines",
    "46": "1 Penny,British Pound,united_kingdom",
    "47": "1 Grosz,Polish Zloty,poland",
    "48": "2 Grosze,Polish Zloty,poland",
    "49": "5 Groszy,Polish Zloty,poland",
    "50": "10 Groszy,Polish Zloty,poland",
    "51": "20 Groszy,Polish Zloty,poland",
    "52": "50 Groszy,Polish Zloty,poland",
    "53": "1 Zloty,Polish Zloty,poland",
    "54": "2 Zlote,Polish Zloty,poland",
    "55": "5 Zlotych,Polish Zloty,poland",
    "56": "1 Kopek,Russian Ruble,russia",
    "57": "2 Pence,British Pound,united_kingdom",
    "58": "5 Kopeks,Russian Ruble,russia",
    "59": "10 Kopeks,Russian Ruble,russia",
    "60": "50 Kopeks,Russian Ruble,russia",
    "61": "1 Ruble,Russian Ruble,russia",
    "62": "2 Rubles,Russian Ruble,russia",
    "63": "5 Rubles,Russian Ruble,russia",
    "64": "10 Rubles,Russian Ruble,russia",
    "65": "1 Cent,Singapore Dollar,singapore",
    "66": "5 Cents,Singapore Dollar,singapore",
    "67": "10 Cents,Singapore Dollar,singapore",
    "68": "5 Pence,British Pound,united_kingdom",
    "69": "20 Cents,Singapore Dollar,singapore",
    "70": "50 Cents,Singapore Dollar,singapore",
    "71": "1 Dollar,Singapore Dollar,singapore",
    "72": "5 Dollars,Singapore Dollar,singapore",
    "73": "5 Cents,South African Rand,south_africa",
    "74": "10 Cents,South African Rand,south_africa",
    "75": "20 Cents,South African Rand,south_africa",
    "76": "50 Cents,South African Rand,south_africa",
    "77": "1 Rand,South African Rand,south_africa",
    "78": "2 Rand,South African Rand,south_africa",
    "79": "10 Pence,British Pound,united_kingdom",
    "80": "5 Rand,South African Rand,south_africa",
    "81": "10 Ore,Swedish Krona,sweden",
    "82": "50 Ore,Swedish Krona,sweden",
    "83": "1 Krona,Swedish Krona,sweden",
    "84": "2 Kronor,Swedish Krona,sweden",
    "85": "5 Kronor,Swedish Krona,sweden",
    "86": "10 Kronor,Swedish Krona,sweden",
    "87": "1 Rappen,Swiss Franc,switzerland",
    "88": "5 Rappen,Swiss Franc,switzerland",
    "89": "10 Rappen,Swiss Franc,switzerland",
    "90": "20 Pence,British Pound,united_kingdom",
    "91": "20 Rappen,Swiss Franc,switzerland",
    "92": "1 2 Franc,Swiss Franc,switzerland",
    "93": "1 Franc,Swiss Franc,switzerland",
    "94": "2 Francs,Swiss Franc,switzerland",
    "95": "5 Francs,Swiss Franc,switzerland",
    "96": "1 2 Dollar,taiwan Dollar,taiwan",
    "97": "1 Dollar,taiwan Dollar,taiwan",
    "98": "5 Dollars,taiwan Dollar,taiwan",
    "99": "10 Dollars,taiwan Dollar,taiwan",
    "100": "20 Dollars,taiwan Dollar,taiwan",
    "101": "50 Pence,British Pound,united_kingdom",
    "102": "50 Dollars,taiwan Dollar,taiwan",
    "103": "1 Satang,Thai Baht,thailand",
    "104": "5 Satang,Thai Baht,thailand",
    "105": "10 Satang,Thai Baht,thailand",
    "106": "25 Satang,Thai Baht,thailand",
    "107": "50 Satang,Thai Baht,thailand",
    "108": "1 Baht,Thai Baht,thailand",
    "109": "2 Baht,Thai Baht,thailand",
    "110": "5 Baht,Thai Baht,thailand",
    "111": "10 Baht,Thai Baht,thailand",
    "112": "2 Cents,Australian dollar,australia",
    "113": "1 Pound,British Pound,united_kingdom",
    "114": "1 Kurus,Turkish Lira,turkey",
    "115": "5 Kurus,Turkish Lira,turkey",
    "116": "10 Kurus,Turkish Lira,turkey",
    "117": "25 Kurus,Turkish Lira,turkey",
    "118": "50 Kurus,Turkish Lira,turkey",
    "119": "1 Lira,Turkish Lira,turkey",
    "120": "1 Cent,US Dollar,usa",
    "121": "5 Cents,US Dollar,usa",
    "122": "1 Dime,US Dollar,usa",
    "123": "1 4 Dollar,US Dollar,usa",
    "124": "2 Pounds,British Pound,united_kingdom",
    "125": "1 2 Dollar,US Dollar,usa",
    "126": "1 Dollar,US Dollar,usa",
    "127": "1 Cent,Canadian Dollar,canada",
    "128": "5 Cents,Canadian Dollar,canada",
    "129": "10 Cents,Canadian Dollar,canada",
    "130": "25 Cents,Canadian Dollar,canada",
    "131": "50 Cents,Canadian Dollar,canada",
    "132": "1 Dollar,Canadian Dollar,canada",
    "133": "2 Dollars,Canadian Dollar,canada",
    "134": "1 Peso,Chilean Peso,chile",
    "135": "5 Cents,Australian dollar,australia",
    "136": "5 Pesos,Chilean Peso,chile",
    "137": "10 Pesos,Chilean Peso,chile",
    "138": "50 Pesos,Chilean Peso,chile",
    "139": "100 Pesos,Chilean Peso,chile",
    "140": "500 Pesos,Chilean Peso,chile",
    "141": "1 Jiao,Chinese Yuan Renminbi,china",
    "142": "5 Jiao,Chinese Yuan Renminbi,china",
    "143": "1 Yuan,Chinese Yuan Renminbi,china",
    "144": "10 Hellers,Czech Koruna,czech_republic",
    "145": "20 Hellers,Czech Koruna,czech_republic",
    "146": "10 Cents,Australian dollar,australia",
    "147": "50 Hellers,Czech Koruna,czech_republic",
    "148": "1 Koruna,Czech Koruna,czech_republic",
    "149": "2 Koruny,Czech Koruna,czech_republic",
    "150": "5 Korun,Czech Koruna,czech_republic",
    "151": "10 Korun,Czech Koruna,czech_republic",
    "152": "20 Korun,Czech Koruna,czech_republic",
    "153": "50 Korun,Czech Koruna,czech_republic",
    "154": "25 Ore,Danish Krone,denmark",
    "155": "50 Ore,Danish Krone,denmark",
    "156": "1 Krone,Danish Krone,denmark",
    "157": "20 Cents,Australian dollar,australia",
    "158": "2 Kroner,Danish Krone,denmark",
    "159": "5 Kroner,Danish Krone,denmark",
    "160": "10 Kroner,Danish Krone,denmark",
    "161": "20 Kroner,Danish Krone,denmark",
    "162": "1 euro Cent,Euro,spain",
    "163": "2 euro Cent,Euro,spain",
    "164": "5 euro Cent,Euro,spain",
    "165": "10 euro Cent,Euro,spain",
    "166": "20 euro Cent,Euro,spain",
    "167": "50 euro Cent,Euro,spain",
    "168": "50 Cents,Australian dollar,australia",
    "169": "1 Euro,Euro,spain",
    "170": "2 Euro,Euro,spain",
    "171": "10 Cents,Hong Kong dollar,hong_kong",
    "172": "50 Cents,Hong Kong dollar,hong_kong",
    "173": "1 Dollar,Hong Kong dollar,hong_kong",
    "174": "2 Dollars,Hong Kong dollar,hong_kong",
    "175": "5 Dollars,Hong Kong dollar,hong_kong",
    "176": "1 Forint,Hungarian Forint,hungary",
    "177": "2 Forint,Hungarian Forint,hungary",
    "178": "5 Forint,Hungarian Forint,hungary",
    "179": "1 Dollar,Australian dollar,australia",
    "180": "10 Forint,Hungarian Forint,hungary",
    "181": "20 Forint,Hungarian Forint,hungary",
    "182": "50 Forint,Hungarian Forint,hungary",
    "183": "100 Forint,Hungarian Forint,hungary",
    "184": "200 Forint,Hungarian Forint,hungary",
    "185": "25 Paise,Indian Rupee,india",
    "186": "50 Paise,Indian Rupee,india",
    "187": "1 Rupee,Indian Rupee,india",
    "188": "2 Rupees,Indian Rupee,india",
    "189": "5 Rupees,Indian Rupee,india",
    "190": "2 Dollars,Australian dollar,australia",
    "191": "10 Rupees,Indian Rupee,india",
    "192": "50 Rupiah,Indonesian Rupiah,indonesia",
    "193": "100 Rupiah,Indonesian Rupiah,indonesia",
    "194": "200 Rupiah,Indonesian Rupiah,indonesia",
    "195": "500 Rupiah,Indonesian Rupiah,indonesia",
    "196": "1000 Rupiah,Indonesian Rupiah,indonesia",
    "197": "5 Agorot,Israeli New Shekel,israel",
    "198": "10 Agorot,Israeli New Shekel,israel",
    "199": "1 2 New Sheqel,Israeli New Shekel,israel",
    "200": "1 New Sheqel,Israeli New Shekel,israel",  
    "201": "1 Centavo,Brazilian Real,brazil",
    "202": "2 New Sheqalim,Israeli New Shekel,israel",
    "203": "5 New Sheqalim,Israeli New Shekel,israel",
    "204": "10 New Sheqalim,Israeli New Shekel,israel",
    "205": "1 Yen,Japanese Yen,japan",
    "206": "5 Yen,Japanese Yen,japan",
    "207": "10 Yen,Japanese Yen,japan",
    "208": "50 Yen,Japanese Yen,japan",
    "209": "100 Yen,Japanese Yen,japan",
    "210": "500 Yen,Japanese Yen,japan",
    "211": "1 Won,Korean Won,south_korea"
}